print("What did you collect?")
print(" ")
print("WATER FOUNTAINS")
WF = input("How many water fountains: ")
WFL = input("Where are they: ")
WFQ = input("Condition of the Water fountains: ")
print(" ")
print("RESTROOMS")
RR=input("How many restroom: ")
RRL=input("Where are they: ")
RRQ=input("Condition of the Restrooms: ")
print(" ")
print("CLASSROOMS")
CR=input("How many classrooms: ")
CRL=input("Classroom Locations: ")
CRQ=input("Condition of classrooms: ")
print(" ")
print("ETC")
OT=input("Number of other things: ")
OTL=input("Location of other things: ")
OTQ=input("Condition of other things: ")
print(" ")
print(" ")
print(" ")
WPC = float(WF)/float(CR)
WPC1 = round(WPC,2)
RPC = float(RR)/float(CR)
RPC1 = round(RPC,2)
print("DATA FOUND")
print("WATER FOUNTAINS:")
print(f"THERE ARE {WF}, THEY ARE IN {WFL} AND THEY ARE IN {WFQ} CONDITION")
print(" ")
print(" ")
print("RESTROOMS:")
print(f"THERE ARE {RR}, THEY ARE IN {RRL} AND ARE IN {RRQ} CONDITION")
print(" ")
print(" ")
print("ETC:")
print(f"THERE ARE {OT}, THEY ARE IN {OTL} AND THEY ARE IN {OTQ} CONDITION")
print(" ")
print(" ")
print("CLASSROOM: ")
print(f"THERE ARE {CR}, THEY ARE IN {CRL}, THEY ARE IN {CRQ} CONDITION")
print(f"THE DENSITY OF WATER FOUNTAINS TO CLASSROOMS IS {WPC1}")
print(f"THE DENSITY OF WATER FOUNTAINS TO CLASSROOMS IS {RPC1}")